"""create M2 schedule and attendance tables

Revision ID: 42f77290cf0f
Revises: b7186c31c373
Create Date: 2026-08-29 14:13:31.066249

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42f77290cf0f"
down_revision: str | None = "b7186c31c373"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "COMPLETED",
                "CANCELLED",
                name="schedulestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedules_class_id"), "schedules", ["class_id"], unique=False)
    op.create_index(op.f("ix_schedules_start_time"), "schedules", ["start_time"], unique=False)
    op.create_index(op.f("ix_schedules_teacher_id"), "schedules", ["teacher_id"], unique=False)
    op.create_table(
        "attendances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UNMARKED",
                "ATTENDED",
                "LEAVE",
                name="attendancestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("operator_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "student_id", name="uq_schedule_student"),
    )
    op.create_index(
        op.f("ix_attendances_schedule_id"), "attendances", ["schedule_id"], unique=False
    )
    op.create_index(op.f("ix_attendances_student_id"), "attendances", ["student_id"], unique=False)
    # 注意：uq_student_class 唯一约束在 M1 迁移中已创建（students/classes 关联）
    # autogenerate 会重复检测，此处不要重复创建。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attendances_student_id"), table_name="attendances")
    op.drop_index(op.f("ix_attendances_schedule_id"), table_name="attendances")
    op.drop_table("attendances")
    op.drop_index(op.f("ix_schedules_teacher_id"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_start_time"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_class_id"), table_name="schedules")
    op.drop_table("schedules")
    # ### end Alembic commands ###
